# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for pollux configurations
Name: jolla-configuration-pollux
Requires:
- pattern:jolla-hw-adaptation-pollux
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

Summary: Jolla Configuration pollux

